name: Checks
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Use NodeJS 12"
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: "Setup npm"
        run: |
          npm set @ejbogantes:registry=https://npm.pkg.github.com/ejbogantes
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.PUBLISH_PACKAGES }}"

      - name: Install dependencies
        run: |
          npm ci
          npx lerna bootstrap

      - name: Run tests # Run tests of all packages
        run: npx lerna exec npm run test
